# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(490, 229)
        MainWindow.setMinimumSize(QtCore.QSize(490, 229))
        MainWindow.setMaximumSize(QtCore.QSize(490, 229))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cbSite = QtWidgets.QComboBox(self.centralwidget)
        self.cbSite.setGeometry(QtCore.QRect(101, 38, 171, 22))
        self.cbSite.setObjectName("cbSite")
        self.cbDomain = QtWidgets.QComboBox(self.centralwidget)
        self.cbDomain.setGeometry(QtCore.QRect(100, 90, 171, 22))
        self.cbDomain.setObjectName("cbDomain")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(29, 92, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(340, 40, 91, 31))
        self.btnStart.setObjectName("btnStart")
        self.fHotmail = QtWidgets.QFrame(self.centralwidget)
        self.fHotmail.setEnabled(False)
        self.fHotmail.setGeometry(QtCore.QRect(20, 130, 451, 71))
        self.fHotmail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fHotmail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fHotmail.setObjectName("fHotmail")
        self.txtPathHotmail = QtWidgets.QLineEdit(self.fHotmail)
        self.txtPathHotmail.setGeometry(QtCore.QRect(10, 19, 351, 31))
        self.txtPathHotmail.setObjectName("txtPathHotmail")
        self.btnSelectPathHotmail = QtWidgets.QPushButton(self.fHotmail)
        self.btnSelectPathHotmail.setGeometry(QtCore.QRect(380, 20, 51, 31))
        self.btnSelectPathHotmail.setObjectName("btnSelectPathHotmail")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reg Acc Capcut"))
        self.label.setText(_translate("MainWindow", "Site"))
        self.label_2.setText(_translate("MainWindow", "Domain"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.txtPathHotmail.setPlaceholderText(_translate("MainWindow", "Path file hotmail"))
        self.btnSelectPathHotmail.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
